### ISSUE TITLE
CreditCardFraudDetection.Trainer load data file error

### ISSUE THREAD

**Issue by rrvenki** [Nukepayload2/machinelearning-samples#18]
For project BinaryClassification_CreditCardFraudDetection\CreditCardFraudDetection.Trainer\ModelBuilder.vb file line number 37 is
_dataSetFile = assetsPath
Change this line to
_dataSetFile = Path.Combine(_assetsPath, "input\creditcard.csv")
This will solve the AuthorizationException error.

**Comment by Nukepayload2** [comment]
@rrvenki If commit https://github.com/Nukepayload2/machinelearning-samples/commit/d73d8eee7447b3dc6d2b65289bbbafe7576f9296 has solved your problem, please close this issue.
